// Generated by https://quicktype.io

export interface SWPlanets {
    name:            string;
    rotation_period: number;
    orbital_period:  number;
    diameter:        number;
    climate:         string;
    gravity:         number;
    terrain:         string;
    surface_water:   number;
    population:      number;
}
